"""Constants used by payment reconciliation."""

CSV_FIELDS = [
    "status",
    "confidence",
    "reason",
    "creator_payment_id",
    "creator_date",
    "creator_amount",
    "creator_customer_id",
    "creator_customer_name",
    "creator_reference",
    "bank_transaction_id",
    "bank_account_id",
    "bank_name",
    "bank_date",
    "bank_amount",
    "bank_reference",
    "bank_description",
    "analytics_customer_id",
    "analytics_customer_name",
    "analytics_bank_transaction_id",
    "analytics_reference",
    "analytics_search_key",
]

UNMATCHED_BANK_EXPORT_FIELDS = [
    "bank_name",
    "bank_account_id",
    "bank_transaction_id",
    "bank_date",
    "bank_amount",
    "bank_reference",
    "bank_description",
    "books_status",
    "books_match_status",
    "books_reconciliation_status",
    "analytics_match_count",
    "analytics_customer_ids",
    "analytics_customer_names",
    "analytics_bank_transaction_ids",
    "analytics_references",
    "analytics_search_keys",
    "raw",
]

CREATOR_EXPORT_FIELDS = [
    "creator_payment_id",
    "creator_date",
    "creator_amount",
    "creator_customer_id",
    "creator_customer_name",
    "creator_reference",
    "raw",
]

REFERENCE_DATE_AMOUNT_MATCH_FIELDS = [
    "match_status",
    "match_reason",
    "matched_reference",
    "matched_reference_source",
    "creator_payment_id",
    "creator_date",
    "creator_amount",
    "creator_customer_id",
    "creator_customer_name",
    "creator_reference",
    "bank_name",
    "bank_account_id",
    "bank_transaction_id",
    "bank_date",
    "bank_amount",
    "bank_reference",
    "bank_description",
    "analytics_customer_ids",
    "analytics_customer_names",
    "analytics_references",
    "analytics_search_keys",
]

ANALYTICS_SEARCH_STOP_TOKENS = {
    "sri",
    "bharath",
    "barath",
    "electrical",
    "electricals",
    "sribharath",
    "sribharathelectricals",
    "bharathelectricals",
    "barathdistributors",
    "payment",
    "transfer",
    "pending",
    "amount",
    "purchase",
    "neft",
    "rtgs",
    "imps",
    "upi",
    "cash",
    "deposit",
    "thillai",
    "nagar",
}
